version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manager
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  java-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/manager
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - mynetwork

volumes:
  db_data:
    driver: local

networks:
  mynetwork: